# -*- coding: utf-8 -*-
"""dz2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a8DjTZSXAkFrryBrYrtm4ljp7XoYpmrD
"""

import datetime
from datetime import datetime
def date_range(date1, date2):
  date1 = datetime.strptime(date1,'%Y-%m-%d')
  date2 = datetime.strptime(date2,'%Y-%m-%d')
  diff = []
  if date2 > date1:
    while date1 <= date2:
      from datetime import timedelta
      diff.append(date1.strftime('%Y-%m-%d'))
      date1 = date1 + timedelta(days=1)
    print(diff)
  else:
    l = 2
    print(l)
date_range('2022-01-01', '2022-01-03')

The_Moscow_Times = 'Wednesday, October 2, 2002'
The_Guardian = 'Friday, 11.10.13'
Daily_News = 'Thursday, 18 August 1977'
import datetime
from datetime import datetime
New_The_Moscow_Times = datetime.strptime(The_Moscow_Times,'%A, %B %d, %Y')
New_The_Guardian = datetime.strptime(The_Guardian,'%A, %d.%m.%y')
New_Daily_News = datetime.strptime(Daily_News,'%A, %d %B %Y')
print(New_The_Moscow_Times,  New_The_Guardian, New_Daily_News)
